// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1MAiZMIS35iwiKlqiABeQsBUDGZplPe8',
    appId: '1:229641290378:web:eb97ca5359f54e53f3a373',
    messagingSenderId: '229641290378',
    projectId: 'vision-plante-dec0b',
    authDomain: 'vision-plante-dec0b.firebaseapp.com',
    storageBucket: 'vision-plante-dec0b.firebasestorage.app',
    measurementId: 'G-SLWLVZ9XVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-91O91ipdxVSZvQdE9JaG_czQaZy_0nw',
    appId: '1:229641290378:android:5739fd29237da9a8f3a373',
    messagingSenderId: '229641290378',
    projectId: 'vision-plante-dec0b',
    storageBucket: 'vision-plante-dec0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKWC_ix3letGlF79IV02GNaLSVneNg8XI',
    appId: '1:229641290378:ios:b46998cd744974d5f3a373',
    messagingSenderId: '229641290378',
    projectId: 'vision-plante-dec0b',
    storageBucket: 'vision-plante-dec0b.firebasestorage.app',
    iosBundleId: 'com.example.visionPlante',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1MAiZMIS35iwiKlqiABeQsBUDGZplPe8',
    appId: '1:229641290378:web:e46516c1327939d7f3a373',
    messagingSenderId: '229641290378',
    projectId: 'vision-plante-dec0b',
    authDomain: 'vision-plante-dec0b.firebaseapp.com',
    storageBucket: 'vision-plante-dec0b.firebasestorage.app',
    measurementId: 'G-LPEV4RLH2D',
  );
}
